### ISSUE TITLE
Independent allocation

### ISSUE THREAD

**Issue by orlp** [orlp/slotmap#10]
Catherine West mentions a crucial missing feature, independent allocation in her RustConf talk, as @nabijaczleweli mentioned to me:

https://youtu.be/aKLntZcp27M?t=2026 

@kyren Could you elaborate what exactly you mean by that?

**Comment by rpjohnst** [comment]
Not kyren, but the problem arises when you want to have a *single* ID space shared across *multiple* arrays, as done elsewhere in the talk.

For example, an ID might represent a whole entity in a game world, which has one entry in a physics slotmap, one entry in an animation slotmap, one entry in an NPC slotmap, etc. This single ID needs to be shared across all the maps so the entity itself can remain a single lightweight integer.

At the same time, each of these slotmaps can independently have or *not* have an entry for a given ID. For example, not every entity has an entry in the NPC slotmap. And this can change over time- some slotmaps might represent transient aspects of entities like status effects.

**Comment by kyren** [comment]
Hey, sorry for not responding earlier!

@rpjohnst has it right, but if it helps, you can see an example of what I meant by independent allocation and how you can use it here: https://github.com/kyren/simplecs/blob/master/src/generational_index.rs

**Comment by orlp** [comment]
@rpjohnst @kyren I believe this sounds a lot like what @eddyb was describing in this reddit comment earlier: https://www.reddit.com/r/rust/comments/8zkedd/slotmap_a_new_crate_for_storing_values_with/e2l1m2c/

He called it secondary maps, and we had a short discussion but I didn't pursue it further. I'll have to think about it a bit more.

My main issue with it is that there's no clear ownership/time of deletion for 'associated components'. In particular, this (phrased in terms of @kyren's example) fails:

    let mut alloc = GenerationalIndexAllocator::new();
    let k = alloc.allocate();
    let mut arr = GenerationalIndexArray::new();
    arr.insert(k, "test");
    alloc.dellocate(k);
    assert_eq!(arr.get(k), None);

**Comment by rpjohnst** [comment]
In the spirit of the more holistic approach used by ECS/data-oriented design/etc., this sort of thing is usually handled as a separate "cleanup" concern, not by any kind of hidden connection or state between the `GenerationalIndexArray` and its "parent" `GenerationalIndexAllocator`. For example, from the blog of the Bitsquid/Stingray engine: http://bitsquid.blogspot.com/2014/09/building-data-oriented-entity-system.html#destroying-components

So your example wouldn't fail like you want, but it often turns out not to be a big deal. Game loops (should) have a very clear order of execution, where the application itself knows far better than the library ever could when and how to clear out stale components, if that's even necessary. (For example it's not in `simpleecs`, because new components will just overwrite dead ones.)

**Comment by kyren** [comment]
> Should this fail? IMO it should. But it might make it expensive and require referencing and potentially locking a mutex for SlotMap or GenerationalIndexAllocator (with ugly interior mutability). Maybe I just have to accept that those associated components will stick around after removal.

Yep, you're absolutely right that that fails.  This was used internally to a larger ECS system that provided the guarantee that deleting an Entity deleted it from every component, by only providing a higher level Entity delete method and ensuring it there.

That's a really good point though and I think it IS surprising that that works, and it really shouldn't.

There are a couple of irritating things you could do like make the id not Copy or Clone and be consumed by removal, but you're right that it's sort of a tricky API problem.

I didn't have time to get into this in the talk, but I kind of figured that it might be tricky to provide a very general API for this which is why I hadn't seen one yet.

Also @rpjohnst point is a good one, that simplecs wouldn't clear out old entities until they were overwritten, which is another potentially bad behavior.

Just for the record, simplecs is not something people should use, it is not meant as an actual library or anything I planned on improving.  It is an extracted form of the WIP ECS that I was working on, there only because I wanted to explain some design points.  Nobody should use it, but it is there if anybody thinks it is interesting.

The most interesting thing about it I think is that my preferred form of ECS design is just the "EC" part and not really the "S" part, becuase ECS is just an interesting sort of data structure.  The problem with this approach is that you really actually sort of want system *scheduling* because you can easily beat performance wise something like relying on RwLocks, but I still enjoy treating ECS as just a very fancy particular sort of data structure.  I also had not seen before the specific technique used to ensure lock order based on typeid, and I thought that might be useful to somebody.  I probably should write a readme explaining this in the project.

**Comment by orlp** [comment]
@kyren So I think I'll go with a design that's subtly different than yours, but achieves the same thing. In your design the allocator is central and you **only** have 'properties'.

My design will be a backwards compatible extension of the current design of `SlotMap`. That is, you still have an actual entry that you insert/remove. Then you can create efficient secondary maps to a `SlotMap` to store properties for an entry. API would look something like this:

    let mut weapons = SlotMap::new();
    let knife = sm.insert("knife");
    let gun = sm.insert("gun");
    let mut damage = sm.new_secondary_map();
    damage.insert(knife, 10);
    damage.insert(gun, 40);

**Comment by kyren** [comment]
> Would that satisfy your concerns?

Yeah, I think so.  I'm not sure because I don't have something concrete to look at, but I think an API like that could work for a large number of use cases.  (I'm making some assumptions about how this will work internally here).

Something that wasn't fully fleshed out before I extracted it into "simplecs" was how to serialize entities including internal references, so that's probably something that we should think about.  You can kind of do it no matter what as long as the key type is Ord or Hash or something like that, and you can, at serialization time, come up with your own mapping of Key to say u64 or something, and then at load you can reverse the process to come up with a mapping from u64 to a new set of Keys.  Maybe that's simple enough, but maybe it's worth thinking of a way that could be easier?

**Comment by orlp** [comment]
> Something that wasn't fully fleshed out before I extracted it into "simplecs" was how to serialize entities including internal references, so that's probably something that we should think about. 

Internal references already work in `slotmap` and can be serialized using the built-in `serde` support without issue. That's one of the killer features of `slotmap`: representing and allowing arbitrary serialization of graph structures.

**Comment by kyren** [comment]
> Internal references already work in slotmap and can be serialized using the built-in serde support without issue. That's one of the killer features of slotmap: representing and allowing arbitrary serialization of graph structures.

Oh, shows how much I know!  How will that work with secondary maps which may not be serialized / deserialized at the same time, does it just work somehow?

**Comment by orlp** [comment]
> Oh, shows how much I know! How will that work with secondary maps which may not be serialized / deserialized at the same time, does it just work somehow?

 It would just work, assuming you serialize/deserialize at the same time.

Since `Key`s are versioned, it would also just work if you don't serialize/deserialize at the same time, but obviously I can't time travel so you're going to get the information from the time you did the operation.

**Comment by orlp** [comment]
I have bad news and good news. After more brainstorming I believe the design of `DenseSlotMap` to be fundamentally incompatible with secondary maps in Rust. The performance just would not be good for the secondary maps, and makes the 'dense' a rather hollow promise.

The good news is that I believe I can make `SlotMap` to have really good iteration speed as well, even when it is very sparse. If I succeed I will simply drop `DenseSlotMap` and only provide `SlotMap`.

@kyren What are your thoughts on providing both `sm.new_secondary_map()` and `sm.new_secondary_sparse_map()`? The latter would have a `HashMap` rather than `Vec` as underlying storage for when you want to have properties for a small portion of elements, rather than the majority. Because with only `new_secondary_map()` you're looking at `O(n)` worst case space usage for each property even if you only store it for one element.

**Comment by rebo** [comment]
Just wondering what would happen if knife is removed from "sm" after

    let mut damage = sm.new_secondary_map();
    let knife_damage = damage.insert(knife, 10);

I presume damage.get(knife_damage) would produce None?

No idea about names, maybe derived_map or composite_map instead of secondary_map?

Also if we consider that specific elements various of a slotmaps make up an 'actual' entity how would it work? The examples above seems to apply a common property to slotmap elements of the same type, rather than coalescing different slotmap types into a single entity.

**Comment by rebo** [comment]
Hi yeah I think I prefer secondary maps as well!

Sorry my 2nd query got mangled somehow. What I meant to say is that I understand that an ECS has a SOA architecture. Is a secondary map designed to support this? And if so how would it be used.

I.e say I have a SlotMap<Position> and a SlotMap<Health> how would a secondary map help construct a consistent entity that had both health and position?

**Comment by rebo** [comment]
I think for some reason left and right angle brackets are being mangled in the comment box! I meant a SlotMap containing  “Health” components and a SlotMap containing  “Position” components. 

I can see from your example how it might work though, thanks!

**Comment by eddyb** [comment]
You need backticks (`) around your code snippets, otherwise the angle brackets are interpreted as HTML tags.
Also, you can edit your own past comments to fix them.

**Comment by orlp** [comment]
Progress update: I've finished removing `DenseSlotMap` in favour of `HopSlotMap`, which is nicely compatible with secondary maps: https://github.com/orlp/slotmap/commit/bdf2e3c1c1e66ea752cd691022462cf561de4793

I'm now focusing on finishing the secondary maps: `slotmap::SecondaryMap` and `slotmap::SparseSecondaryMap`.

**Comment by Nimelrian** [comment]
A month went by and I just saw 7e3527f3750a8fe2ca666dd27a5082923a319dd8! I guess a release with secondary maps isn't far away anymore? 😄

**Comment by orlp** [comment]
@Nimelrian Correct. I'm still working on `SparseSecondaryMap` backed by a `HashMap` and changing `Key` into `Key<M>` to prevent cross-slotmap usage.

**Comment by Nimelrian** [comment]
I'm kinda new to Rust and waited for this feature to finally get a little bit more into it, so I'm probably not the best person to give feedback. I may be able to take a look over it in terms of "how easy is it for a beginner to get something done with the library/feature", but don't let that get into the way of a release.

The only thing I'd like to see as of now would be unit tests ;)

**Comment by Nimelrian** [comment]
I used the current master branch to play around a little bit and so far the ergonomics feel right in terms of creating/inserting values.

As you already said, removing a value from the main `SlotMap` does not remove it from any secondary maps.  This obviously puts additional load on the lib user since he's responsible for keeping this invariant (`SecondaryMap`s shouldn't contain keys which aren't stored in a `SlotMap`) intact.

As I said, I'm still new to Rust, but sometimes questions from "newcomers" often inspire solutions one may not have thought of before. Wouldn't it be possible to implement some variation of the Observer/Observable pattern? Though I'd guess that the borrow checker may have a problem with that. As I said, I lack the deeper knowledge.

Other than that, it's looking good so far. Maybe @kyren is able to chime in as well, since she mentioned this feature was missing in general. Is keeping the invariant intact important in the gamedev industry?

**Comment by orlp** [comment]
> As you already said, removing a value from the main `SlotMap` does not remove it from any secondary maps. This obviously puts additional load on the lib user since he's responsible for keeping this invariant (`SecondaryMap`s shouldn't contain keys which aren't stored in a `SlotMap`) intact.

Not necessarily. A `SecondaryMap` does not leak memory even if the old key is never removed.

Either way, it's impossible to guarantee this through Rust alone without breaking the cornerstone of why `SlotMap` and `SecondaryMap`s are so useful: they are independent. As soon as you introduce some dependency of one on the other you are looking at multiple borrows, locking, exclusivity, etc...

**Comment by orlp** [comment]
Fixed with release 0.3.0.

@kyren I would love it if you'd take a moment to go over the design I've implemented and let me know if it still is missing something that you really want.

It would also be really nice if could you also update the part in your blog post (https://kyren.github.io/2018/09/14/rustconf-talk.html) talking about `slotmap` that it now provides the features you were missing (assuming my API is satisfactory).
