### ISSUE TITLE
Some questions about 0.3.0 version of source code

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [orlp/slotmap#25]
I have several questions about the source code:

1. Why the next_free field of SlotUnion is `u32` rather than `usize`?
2. In [src/secondary.rs#275](https://github.com/orlp/slotmap/blob/master/src/secondary.rs#L275), should we reserve space with `Vec::reserve` before the push iteration?
3. In lib.rs, what is the idea behind `is_older_version`?

**Comment by orlp** [comment]
> Why the next_free field of SlotUnion is `u32` rather than `usize`?

To reduce memory overhead.

> In src/secondary.rs#275, should we reserve space with `Vec::reserve` before the push iteration?

That wouldn't hurt, yes.

> In lib.rs, what is the idea behind `is_older_version`?

To determine whether one version is older than another. You may wonder why we don't use simple comparison.

As an example let's say that `version` were stored in a 4-bit integer. Then after 14 comes 15, so 14 is older and 15 is newer. But after 15 comes... 0! Since versions can wrap around we have to be more careful in our comparison. There's still some version issues you can't detect with this if you keep exceptionally old keys around and re-use the same slot an incredible amount of times, but that's exceedingly rare.
