### ISSUE TITLE
Thoughts on immutable versions?

### ISSUE THREAD

**Issue by jessegrosjean** [orlp/slotmap#34]
Would it be within project scope to add some [im](https://docs.rs/im/13.0.0/im/) backed maps? I would like to store data in SlotMap, but I would also like to cheaply clone the map to create snapshots and pass to other threads.

**Comment by orlp** [comment]
The raison d'être for `slotmap` is the fast implementation it provides due to internally just being some constant time operations on `Vec`, while being able to safely re-use memory when elements get removed.

In an persistent version both of those reasons essentially disappear. Unless you specifically had the perfect data structure in mind that allows you to implement this in an exceedingly efficient way, I do not see the advantage of a persistent slotmap over a regular persistent map plus using an monotonously increasing counter as your keys.

**Comment by jessegrosjean** [comment]
Thanks for your response and I guess you are probably right.
