### ISSUE TITLE
[Feature Request] SecondaryBitSet

### ISSUE THREAD

**Issue by XBagon** [orlp/slotmap#82]
I'm using `slotmap` for a graph structure, which I think `petgraph` would be overkill to retrofit for. And after wondering when `SecondaryMap`s are ever useful, to being a huge fan of them, I'm now at the point where I asked myself what `petgraph` uses for marking nodes as visited in a DFS/BFS and then found [this](https://docs.rs/petgraph/latest/petgraph/visit/trait.VisitMap.html#impl-VisitMap%3CIx%3E-for-FixedBitSet).

So my feature request would be having a [fixedbitset](https://crates.io/crates/fixedbitset) as a space-efficient `bool`-SecondaryMap. 
Would this feature fit this crate? I might be able to take a stab at it.

**Comment by orlp** [comment]
I don't think it makes a whole lot of sense, at least within the context of `slotmap`. Since each slot needs to keep track of the version, there would be no saving of any meaningful space since almost all data would be used for storing versions. The only way it would make sense is if you ignore the version entirely, and only use the index of a key. I don't feel this is in the spirit of slotmap.

In slotmap 2.0 I will expose the index and version explicitly (which I was initially hesitant for, to keep flexibility in internal representation). Then you can use a regular bitset and use the index explicitly.

**Comment by XBagon** [comment]
Right, I forgot about the version. Good point. I'm looking forward of doing it myself in 2.0 then :). Thanks!
For the moment I will stick with `SecondaryMap<K, ()>` then.
